import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/style.css";
import "@/styles/plug.css";
import "@/styles/bootstrap.css";
import "@/styles/animation.css";
import "@/styles/header.css";
import "@/styles/nav.css";
import "@/styles/forms.css";
// import "@/styles/style2.css";
import "@/styles/mobile.css"; 
import '@/styles/site-elements.css'
import "@/styles/reset.css";
import "@/styles/typography.css"
import "bootstrap-icons/font/bootstrap-icons.css";
import Header from "@/components/header";
import '@fortawesome/fontawesome-free/css/all.min.css'
import Footer from "@/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`loaded ${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
